### PR TITLE
Recursive implementation following the same paradigm

### PR DESCRIPTION
**Pull request by thehoneymad**
The changes I made are all in a new file called  number-to-bangla-rec.js. You can opt to keep both or merge. Changes I would like to suggest:

1. Following the same lookahead pattern, a LR parse now.
2. Recursive solution to generate the number text.
3. Used local functions in the middle to reuse. 
4. The selection in the middle can be shortened a lot. I got bored. :bowtie: 
5. Number to string conversion minimized, performance boost of a millisecond. 🏃 🏃 
6. Now we can go as long as people want us to go. 🎉 

I don't write JS at all. So, begging pardon in advance for unintentional mistakes. Found this as a random nerd snipe and jumped in.

### CODE REVIEW

**Comment by tsaqib** [comment]
Requires modern browsers.

**Comment by thehoneymad** [comment]
No idea about browser compatibility, probably my JS knowledge lacking. Lemme know if you make it back portable. we can replace the arrow functions with regular functions I guess.

**Comment by tsaqib** [comment]
I wonder if `const` and local functions are compatible with 2013-ish browsers?

**Comment by thehoneymad** [comment]
local functions should be since we can rewrite them as just regular JS functions and the implementation should work just fine. 

About const...no idea.

**Pull request merged**
